### ISSUE TITLE
Error is returned when I try to run `yo verb:doc foo.md`

### ISSUE THREAD

**Issue by phillipalexander** [verbose/generator-verb#12]
The following error is returned when I try to run `yo verb:doc foo.md`

``` sh
events.js:85
      throw er; // Unhandled 'error' event
            ^
AssertionError: /Users/phillipalexander/.nvm/versions/node/v0.12.0/lib/node_modules/generator-verb/node_modules/verb-readme-includes/templates/foo.md doesn't exist
    at EditionInterface.module.exports [as read] (/Users/phillipalexander/.nvm/versions/node/v0.12.0/lib/node_modules/generator-verb/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/read.js:13:3)
    at VerbGenerator.template (/Users/phillipalexander/.nvm/versions/node/v0.12.0/lib/node_modules/generator-verb/node_modules/yeoman-generator/lib/actions/actions.js:191:34)
    at VerbGenerator.files (/Users/phillipalexander/.nvm/versions/node/v0.12.0/lib/node_modules/generator-verb/doc/index.js:34:8)
    at /Users/phillipalexander/.nvm/versions/node/v0.12.0/lib/node_modules/generator-verb/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by jonschlinkert** [comment]
thanks for the heads up
